### ISSUE TITLE
Fix the warnings and enable fatal warnings in CI

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-collections#486]
Follow-up to https://github.com/typelevel/cats-collections/pull/485.

https://github.com/typelevel/cats-collections/blob/2bf3b430484c7788f3cadae5835690fb0cbd53c9/build.sbt#L17

**Comment by satorg** [comment]
@armanbilge @gemelen may I take this one?

**Comment by PATIENCE-ONAH** [comment]
Hi @armanbilge, it seems this issue has been resolved as there were no warnings after I ran test.  Do I go ahead and enable fatal warning or maybe I'm missing something.

**Comment by armanbilge** [comment]
Hi @PATIENCE-ONAH, thanks for your interest!

> it seems this issue has been resolved

Unfortunately not, this issue has still not been resolved.

> there were no warnings after I ran test

The warnings occur before running tests, during the compilation phase. You can see them here in CI:
https://github.com/typelevel/cats-collections/actions/runs/18596764558/job/53024923908#step:12:25

**Comment by satorg** [comment]
Ah yeah, this one... I started off briskly and fixed some of the files. Then got stuck with `TreeList`. I don't remember what the issue was exactly since it was quite long ago. Perhaps, there were differences between Scala2 and Scala3 compilers that I didn't manage to overcome.

**Comment by PATIENCE-ONAH** [comment]
> Hi [@PATIENCE-ONAH](https://github.com/PATIENCE-ONAH), thanks for your interest!
> 
> > it seems this issue has been resolved
> 
> Unfortunately not, this issue has still not been resolved.
> 
> > there were no warnings after I ran test
> 
> The warnings occur before running tests, during the compilation phase. You can see them here in CI: https://github.com/typelevel/cats-collections/actions/runs/18596764558/job/53024923908#step:12:25

Okay, Thank you. I will look at it again

**Comment by satorg** [comment]
Turns out it was quite straightforward: #768.
Still not sure what went wrong last time.

Note: there are still a handful of compiler warnings in the `tests` module. I can take on them another day.

cc @armanbilge @PATIENCE-ONAH
